version: "3.9"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=drankBeheer
      - POSTGRES_USER=drankbeheer
      - POSTGRES_PASSWORD=drankbeheer
    # volumes:
      # - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
  web:
      build: .
      # command: gunicorn -b 0.0.0.0:8000 drankBeheer.wsgi
      # command: python manage.py collectstatic
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/drankBeheer
      ports:
        - "8000:8000"
      depends_on:
        - db
