# Generated by Django 3.1.5 on 2021-01-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beheer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leider',
            name='volgorde',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
