# Generated by Django 3.1.5 on 2021-01-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beheer', '0003_betaling_hoeveelheid'),
    ]

    operations = [
        migrations.AddField(
            model_name='prijsklasse',
            name='naam',
            field=models.CharField(default='standaard', max_length=50),
            preserve_default=False,
        ),
    ]
