# Generated by Django 3.1.5 on 2021-01-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beheer', '0004_prijsklasse_naam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leider',
            name='naam',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='prijsklasse',
            name='naam',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
