# Generated by Django 3.1.5 on 2021-01-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beheer', '0005_auto_20210105_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='betaling',
            old_name='Leider',
            new_name='leider',
        ),
        migrations.AlterField(
            model_name='telling',
            name='aantalNormaal',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='telling',
            name='aantalZwaar',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
