# Generated by Django 3.1.5 on 2021-01-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beheer', '0006_auto_20210106_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telling',
            name='aantalNormaal',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='telling',
            name='aantalZwaar',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
