# Generated by Django 3.1.5 on 2021-01-11 12:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('beheer', '0010_auto_20210106_1943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leider',
            options={'ordering': ['volgorde']},
        ),
        migrations.AddField(
            model_name='betaling',
            name='datum',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telling',
            name='datum',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
