# Generated by Django 3.1.5 on 2021-01-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beheer', '0011_auto_20210111_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leider',
            name='volgorde',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
