# Generated by Django 3.1.6 on 2021-02-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beheer', '0012_auto_20210111_1710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='betaling',
            options={'verbose_name_plural': 'Betalingen'},
        ),
        migrations.AlterModelOptions(
            name='telling',
            options={'verbose_name_plural': 'Tellingen'},
        ),
        migrations.AlterField(
            model_name='leider',
            name='volgorde',
            field=models.IntegerField(blank=True, default=500),
        ),
    ]
