# Generated by Django 3.1.8 on 2021-09-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beheer', '0013_auto_20210210_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='leider',
            name='actief',
            field=models.BooleanField(default=True),
        ),
    ]
